### ISSUE TITLE
Errors compiling with Visual Studio 2019 and Win 10 SDK 10.0.19041.0

### ISSUE THREAD

**Issue by Gromph** [microsoft/MFCStoreClient#1]
Repro:

1. I opened the solution with Visual Studio 2019 version 16.9.4. 
2. It prompted to Retarget Projects to Windows SDK 10.0.19041.0 and Platform Toolset v142.  I clicked ok to let it.
3. Changed cpu to x64
4. Set Packaging project as startup
5. Pressed F5 and got lots of errors starting with:
WindowsStore\WindowsStoreImpl.h(24,56): error C2039: 'Store': is not a member of 'Windows::Services'
WindowsStore\WindowsStoreImpl.h(24,56): error C3083: 'Store': the symbol to the left of a '::' must be a type
WindowsStore\WindowsStoreImpl.h(24,63): error C2039: 'StoreContext': is not a member of 'Windows::Services'

See build.log for more errors and warnings.
[build.log](https://github.com/microsoft/MFCStoreClient/files/6339463/build.log)

I'm looking for a complete example of a Desktop Bridge application accessing the Windows Store API using C++/WinRT

**Comment by stammen** [comment]
@Gromph I pushed the fix for building with 10941
